=== Architectures REST
* *REST* : *RE*presentational *S*tate *T*ransfer
** Type d’architecture pour systèmes hypermédia distribués
** Inventé par Roy Fielding en 2000

=== Architectures REST
* Architecture 
** Client / Serveur
** Stateless : chaque requête au serveur contient toutes les informations nécessaires à son traitement
** Basée sur la manipulation de ressources identifiées par leur URI
*** création,
*** modification,
*** suppression

=== Architectures REST

* Un système basé sur cette architecture est qualifié de *RESTful*
* Avantages
** Découplage client/serveur
** Scalabilité du serveur
** Mise en cache des ressources
* Inconvénients
** Pas d'indexation du site facilement
** Gestion de la sécurité plus difficile (code côté client)
** Traffic réseau supplémentaire



=== Architectures REST
* AngularJS promeut les architectures REST
** Applications riches entièrement gérées côté client
** Manipulation de ressources REST
** Utilisation possible du stockage local
* 2 mécanismes d'interaction avec le serveur
** `$http` : requêtes AJAX simples
** `$resource` : abstraction de ressources REST pour faciliter leur manipulation

=== Le service $http
* Le service `$http` est construit autour de la notion de promesses (*promise*)
** Représente une valeur calculée de manière asynchrone
** Implémentée par le service AngularJS `$q`
*** remplace la  “Pyramid of Doom” par des promise
** Comparable à la classe `Future<T>` en Java

[NOTE.speaker]
--
$q est inspiré de https://github.com/kriskowal/q[l'API "Q" de Kris Kowal^]
--

=== Le service $http
* Avantages
** Interface plus réactive
** Utilisation transparente dans les modèles et les templates
** Possibilité de composer plusieurs opérations asynchrones

=== Le service $http
* Le service `$http`
** prend en paramètre une map de configuration 
** renvoie une *promise* exposant deux méthodes callback *sucess* et *error*

```javascript
$http({method:'GET', url:'/foo'}).
    success(
        function(data, status, headers, config, statusText) {
            // Appelée lorsque la réponse est disponible
            // et valide (code HTTP 2xx)
        }
    ).
    error(
        function(data, status, headers, config, statusText) {
            // Appelée en cas d'erreur technique, 
            // ou de réponse négative du serveur
        }
    );
```

=== Le service $http
* Principaux paramètres de configuration de la requête
** [string] *method* : 'GET', 'POST'... 
** [string] *url* : '/foo'
** [map] *params* : {foo:'bar'}
** [map] *headers* : {accept:'text/html'}
** [string/object] *data* : {values:['a','b'],...}

=== Le service $http
* Paramètres des fonctions callback *success* / *error*
** [string/object] *data* : le corps du message
** [number] *status* : code de retour HTTP
** [fonction] *headers* : fonction d'accès aux headers
** [map] *config* : la configuration utilisée pour la requête
** [string] *statusText* : Le message de l'état de la réponse

=== Le service $http
* Exemple : récupération de commandes depuis un contrôleur

```javascript
$scope.commandes = [];
$scope.errorMsg = '';

$scope.getCommandes = function() {

    $http({method:'GET', url:'/commandes'}).

        success(function(data) {
            $scope.commandes = data;		
            $scope.errorMsg = '';
        }).

        error(function(data, status) {
            $scope.commandes = [];
            $scope.errorMsg = 'Error ' + status;
        });
}
```



=== Le service $http
* Le service `$http` propose également une API simplifiée
** `get(url, [config])`
** `jsonp(url, [config])`
** `post(url, data, [config])`
** `put(url, data, [config])`
** `head(url, [config])`
** `delete(url, [config])`

```javascript
$http.jsonp("http://monServeur/Commandes?callback=JSON_CALLBACK").
    success(function(data) {
        $scope.commandes = data;		
});
```

[NOTE.speaker]
--
Le nom du callback doit être la chaine JSON_CALLBACK qui sera remplacé à l'appel par le nom de la méthode correspondante.
https://angularjs.org/greet.php?callback=JSON_CALLBACK&name=Super%20Hero
https://angularjs.org/greet.php?callback=angular.callbacks._0&name=Super%20Hero
http://plnkr.co/edit/qTFQ3HshfpYqVxlpALUo[demo^]
--

=== Le service $resource
* Angular fournit une surcouche au service $http,
* Le service `$resource` permet d'abstraire et de simplifier l'interaction avec des ressources exposées en REST
** "Convention over configuration"
** Basé sur le service `$http`
** Objet de type "ActiveRecord"

=== Le service $resource
* Syntaxe du service `$resource`

```javascript
$resource(url, [params], [actions]);
```

* Paramètres (détaillés plus loin)
** [string] *url* : l'URL de la ressource REST (obligatoire)
** [map] *params* : valeurs par défaut pour les bindings d'URL
** [map] *actions* : actions personnalisées additionnelles

=== Le service $resource
* Installation
** Inclure le script *angular-resource.js*
** Déclarer une dépendance vers le module `ngResource`

```javascript
var myModule = angular.module('myModule', ['ngResource']);
```

=== Le service $resource : Déclaration d'une ressource
* Une ressource se déclare via la méthode `factory` d'un module

```javascript
var CommandeApp = angular.module('CommandeApp', ['ngResource']);
CommandeApp.factory('Commandes', ['$resource',
   function($resource) {
      return $resource('/rest/commandes');
   }
]);
```

=== Le service $resource : Déclaration d'une ressource
* Elle peut alors être injectée dans d'autres entités AngularJS 
** Contrôleurs, services, modules, directives...

```javascript
CommandeApp.controller('CommandeListCtrl', ['$scope', 'Commandes', 
  function ($scope, Commandes) {
    $scope.commandes = Commandes.query();
  }
]);
```



=== Le service $resource : Paramètres - URL
* L'URL peut contenir des paramètres de binding
** Forme ":binding" (ex: "/rest/commandes/:id")
** Possibilité d'indiquer des valeurs par défaut (constantes ou extraites des propriétés de l'objet)
** Les paramètres non associés à un binding sont passés sous forme de paramètres d'URL (?foo=bar)

```javascript
return $resource( 
    '/rest/commandes/:group/:id',        
    { 
      group:'friends', // constante
      id:'@userId', // propriété "userId" de l'objet
      foo:'bar' // paramètre additionnel sans binding
    } 
);
```



=== Le service $resource : Paramètres - Actions
* Une ressource expose différentes *actions*
* Une action représente une configuration particulière des paramètres d'appel du service `$http`
** `method`, `url`, `params`
* Une action peut être invoquée
** A partir de la ressource, en lui passant une instance
** Directement sur une instance particulière
  
    (l'action est alors préfixée par `$`)

* Les actions retournent un résultat synchrone qui sera complété de manière asynchrone afin d'utiliser une notation pratique



=== Le service $resource : Paramètres - Actions
* Chaque ressource AngularJS expose 5 actions préconfigurées permettant la création, la mise à jour, la suppression et la recherche de ses instances
** `get`, `save`, `remove`, `delete`, `query`
* Paramétrage des actions préconfigurées
** `url` : l'URL de la ressource
** `method` : 
*** `get`, `query` → GET
*** `remove`, `delete` → DELETE
*** `save` → POST



=== Le service $resource : Paramètres - Actions
```javascript
$scope.commandes = Commande.query(function(commandes) {
	var firstCommande = commandes[0];
	firstCommande.$delete();
});
```

* De nouvelles actions peuvent être définies
** Dernier paramètre de la factory `$resource`
** Possibilité de définir le type de requête HTTP et les paramètres par défaut

```javascript
return $resource( '/rest/commandes/:id', {id:'@userId'}, 
    { export: { method: 'GET', params: {format:'pdf'} },
        call: {method: 'GET', params: {where:'home'} } }
);
```



=== Le service $resource : Paramètres - Actions
* A l'appel d'une action (préconfigurée ou personnalisée), il est possible de passer 3 paramètres optionnels :
** [map] *params* : paramètres d'appel, fusionnés avec les paramètres par défaut de l'action et ceux de la ressource
** [fonction] *success* : callback de réussite
** [fonction] *error* : callback d'erreur

```javascript
var marvin = Commande.get( {id:42} ); // params

marvin.$delete(
    // fonction callback en cas de succès
    function() {
        console.log("Commande deleted.");
    });
```

include::../includes/TPs.adoc[]
