=== Authentification sur une SPA
* Approches au niveau du formulaire d'identification
** SSO : formulaire déporté sur un service différent
** Page de login : navigation après validation du formulaire
** Login intégré : formulaire intégré à l'application

[NOTE.speaker]
--
SSO : Single Sign On
--

=== Authentification sur une SPA
* Approches au niveau de la transmission de la session
** Cookie de session : nécessite du statefull côté serveur
** Cookie avec credentials : nécessite un bon cryptage
** Headers dans chaque requêtes
** Passage d'un token en paramètre des requêtes
  
=== Authentification sur une SPA
* Toutes les méthodes ont des avantages et des inconvénients mais certaines nécessités reviennent
* Quelque soit la sécurité mise en oeuvre côté client (JS), il faudra *toujours* implémenter une couche de sécurité côté serveur

=== En-têtes HTTP
* Le service $http ajoute déjà automatiquement des en-têtes HTTP
* On peut y accéder au moment de la configuration de l'application via `$httpProvider.defaults.headers`

=== En-têtes HTTP
** On pourra par exemple ajouter un entête sur les requêtes de type GET

```javascript
$httpProvider.defaults.headers.get = { 'My-Header' : 'value' }
```

* On peut aussi y accéder au moment de l'exécution via `$http.defaults.headers`

```javascript
$http.defaults.headers.common =
    { 'Content-Type' : 'application/xml' }
```

=== Intercepteurs HTTP
* Les intercepteurs de filtrent les requêtes et les réponses de manière synchrone ou asynchrone à l'aide du service `$q`
* Il faut enregistrer les factory d'intercepteurs avec leurs dépendances dans l'array `$httpProvider.interceptors`

=== Intercepteurs HTTP

```javascript
$httpProvider.interceptors.push(
    function($q, dependency1, dependency2) {
        return {
            request: function(config)
                { return config || $q.when(config); },
            requestError: function(rejection)
                { return $q.reject(rejection); },
            response: function(response)
                { return response || $q.when(response); },
            responseError: function(rejection) 
                { return $q.reject(rejection); }
        };
    }
);
```

=== Intercepteurs HTTP
* Un exemple d'intercepteur qui stocke localement :
** Les headers de la dernière réponse OK reçue
** Le statut HTTP de la dernière réponse KO reçue

```javascript
$httpProvider.interceptors.push(function($q) {
    return {
        response: function(response) {
            localStorage.setItem('latestHeaders', response.headers);
            return response || $q.when(response);
        },
        responseError: function(rejection) {
            localStorage.setItem('latestRejectionStatus',
                rejection.status);
            return $q.reject(rejection);
        }
    };
});
```

=== L'approche JWT
* JSON Web Token (JWT) est un standard ouvert pour échanger de l'information de manière sécurisée via un jeton signé.
* Un jeton JWT est composée de trois parties :
** un entête,
** une charge utile et
** une signature.

=== L'approche JWT
==== L'en-tête
* L'en-tête indique l'algorithme utilisé pour la signature :

```
header = '{"alg":"HS256","typ":"JWT"}'
```

=== L'approche JWT
==== La charge utile

* La charge utile est variable en fonction de l'application, mais il est indiqué dans les spécifications de JWT d'inclure une empreinte temporelle à la création +
(un "iat" ou encore "issued at" en anglais):

```
payload = '{"loggedInAs":"admin","iat":1422779638}'
```

=== L'approche JWT
==== La signature

* La signature est calculée via une concaténation de l'en-tête et de la charge utile, encodés en base64url, et séparés par un point. +
La signature elle même est obtenue via l'algorithme spécifié dans l'en-tête appliqué au jeton et à la clé :

```
key           = 'secretkey'
unsignedToken = encodeBase64(header) + '.' + encodeBase64(payload)
signature     = HMAC-SHA256(key, unsignedToken)
```

[NOTE.speaker]
--
La signature est généré coté serveur, est il n'y as pas besoin de partagé la clef de Chiffrage qui peut changer très régulièrement
--

=== L'approche JWT
==== Le Token

* Le token est généré a partir de la concaténation des trois parties encodé en base64, séparré par `.` :

```
token = encodeBase64(header) + '.' 
    + encodeBase64(payload) + '.' 
    + encodeBase64(signature) 
```

* le token vaut :  +
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2d +
nZWRJbkFzIjoiYWRtaW4iLCJpYXQiOjE0MjI3Nzk2Mzh +
9.gzSraSYS8EXBxLN_oWnFSRgCzcmJmMjLiuyu5CSpyHI 

=== L'approche JWT
==== L'utilisation

* Lors de l'authentication, 
** quand l'utilisateur c'est correctement identifé, 
** un JSON Web Token est retourné au client 
** il est sauvegardé localement 
*** dans le local storage,
*** dans le session storage
*** ou dans un cookie 

[NOTE.speaker]
--
au lieu de l'approche traditionnelle de création de session sur le serveur et le retour par cookie.
--

=== L'approche JWT
==== L'utilisation

* Quand l'utilisateur veux acceder à une route ou une resource protégée, le "user agent" transmettra le JWT, typiquement en temps qu'en-tête Authorization utilisant le schema Bearer.

```
Authorization: Bearer <token> 
```

=== L'approche JWT
==== L'utilisation

* c'est un méchanisme d'authentication stateless car l'état de l'utilisateur n'est jamais stocké en mémoire.
* Le serveur vérifiera la validité du Token JWT contenu dans l'en-tête Autaurisation.
* La charge utile des jetons JWTs est un objet, elle contient toute l'information nécessaire, reduisant le besoin de requêter la BDD systématiquement.
* Il faut faire attention au possibilité de rejeut avec un me token JWT


include::../includes/TPs.adoc[]
